"""baseline: current schema as of the multi-site release

Revision ID: 05a71b7465a5
Revises: 
Create Date: 2026-08-21 18:08:12.323848

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '05a71b7465a5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_usage',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.String(length=40), nullable=False),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('key_hash')
    )
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_site_occurred_at', 'audit_log', ['site_id', 'occurred_at'], unique=False)
    op.create_table('authorized_operator',
    sa.Column('operator_id', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('operator_id')
    )
    op.create_index('idx_authorized_operator_site_id', 'authorized_operator', ['site_id'], unique=False)
    op.create_table('sensor_registry',
    sa.Column('sensor_id', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('sensor_type', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('azimuth_reference_deg', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('active', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('sensor_id')
    )
    op.create_index('idx_sensor_registry_site_id', 'sensor_registry', ['site_id'], unique=False)
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('track_uid', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.String(length=40), nullable=False),
    sa.Column('last_seen', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('classification', sa.String(length=20), server_default='unknown', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('position_uncertainty_m', sa.Float(), nullable=True),
    sa.Column('maneuver_probability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_uid')
    )
    op.create_index('idx_track_site_status_last_seen', 'track', ['site_id', 'status', 'last_seen'], unique=False)
    op.create_index('idx_track_status_last_seen', 'track', ['status', 'last_seen'], unique=False)
    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('polygon', sa.Text(), nullable=False),
    sa.Column('min_altitude_m', sa.Float(), nullable=True),
    sa.Column('max_altitude_m', sa.Float(), nullable=True),
    sa.Column('active', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_zone_site_id', 'zone', ['site_id'], unique=False)
    op.create_table('detection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('sensor_id', sa.String(length=100), nullable=False),
    sa.Column('sensor_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.String(length=40), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('azimuth_deg', sa.Float(), nullable=True),
    sa.Column('range_m', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('georeferenced', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_detection_site_id', 'detection', ['site_id'], unique=False)
    op.create_index('idx_detection_timestamp', 'detection', ['timestamp'], unique=False)
    op.create_index('idx_detection_track_id', 'detection', ['track_id'], unique=False)
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('incident_uid', sa.String(length=64), nullable=False),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default='low', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.String(length=40), nullable=False),
    sa.Column('closed_at', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_uid')
    )
    op.create_index('idx_incident_site_id', 'incident', ['site_id'], unique=False)
    op.create_index('idx_incident_track_id', 'incident', ['track_id'], unique=False)
    op.create_index('idx_incident_zone_id', 'incident', ['zone_id'], unique=False)
    op.create_table('track_kalman_state',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('ref_lat', sa.Float(), nullable=False),
    sa.Column('ref_lon', sa.Float(), nullable=False),
    sa.Column('models', sa.Text(), nullable=False),
    sa.Column('mode_probabilities', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('track_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_kalman_state')
    op.drop_index('idx_incident_zone_id', table_name='incident')
    op.drop_index('idx_incident_track_id', table_name='incident')
    op.drop_index('idx_incident_site_id', table_name='incident')
    op.drop_table('incident')
    op.drop_index('idx_detection_track_id', table_name='detection')
    op.drop_index('idx_detection_timestamp', table_name='detection')
    op.drop_index('idx_detection_site_id', table_name='detection')
    op.drop_table('detection')
    op.drop_index('idx_zone_site_id', table_name='zone')
    op.drop_table('zone')
    op.drop_index('idx_track_status_last_seen', table_name='track')
    op.drop_index('idx_track_site_status_last_seen', table_name='track')
    op.drop_table('track')
    op.drop_index('idx_sensor_registry_site_id', table_name='sensor_registry')
    op.drop_table('sensor_registry')
    op.drop_index('idx_authorized_operator_site_id', table_name='authorized_operator')
    op.drop_table('authorized_operator')
    op.drop_index('idx_audit_log_site_occurred_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('site')
    op.drop_table('api_key_usage')
    # ### end Alembic commands ###
